// Workshop notebooks (rendered on /notebooks/<slug>/, downloadable from
// public/notebooks/, and openable in Colab). The .ipynb files are generated by
// scripts/build-notebooks.py.

export interface NotebookMeta {
  slug: string;        // page route: /notebooks/<slug>/
  title: string;
  file: string;        // file in public/notebooks/
  day: number;         // linked curriculum day
  blurb: string;
}

export const notebooks: NotebookMeta[] = [
  {
    slug: 'evaluation-lab',
    title: 'Evaluation Lab',
    file: 'evaluation-lab-template.ipynb',
    day: 3,
    blurb:
      'A template notebook for building your project’s evaluation — discrimination, calibration, clinical utility, subgroup disaggregation, power, and leakage/shortcut probing.',
  },
  {
    slug: 'methods-lab',
    title: 'Methods Lab',
    file: 'methods-lab-template.ipynb',
    day: 4,
    blurb:
      'A template notebook for building and comparing methods for your project — baseline, stronger models, a representation/foundation approach, and a comparison harness reusing your Day 3 evaluation moves.',
  },
];

export function getNotebook(slug: string): NotebookMeta | undefined {
  return notebooks.find((n) => n.slug === slug);
}

// GitHub repo path used to open a notebook in Google Colab.
const COLAB_REPO = 'ahli-org/ahli-summer-camp-website/blob/main/public/notebooks';

export function colabUrl(file: string): string {
  return `https://colab.research.google.com/github/${COLAB_REPO}/${file}`;
}
